### ISSUE TITLE
Intermittent test failure: supports updating search params when tabs are clicked

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#10099]
Seen locally

```js
      190 | ) => {
      191 |   render(<Subject {...{ experiments }} />);
    > 192 |   await waitForElementToBeRemoved(() => screen.getByTestId("page-loading"));
          |                                  ^
      193 | };
      194 |

      at waitForElementToBeRemoved (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for-element-to-be-removed.js:22:24)
      at renderAndWaitForLoaded (src/components/PageHome/index.test.tsx:192:34)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:100:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4250)

**Comment by jaredlockhart** [comment]
The page home tests are now all disabled, this can be closed.
