### ISSUE TITLE
pluggy.manager.PluginValidationError, celery, and billiard

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#1017]
I create a fresh new virtualenv based on Python 3.7.2 and `pip install app/requirementst/default.txt` and this happens when I try to run `pytest`. 

<details>
<summary>Console output</summary>
EXPERIMENTER/experimenter/app  master ✔
▶ pytest
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/manager.py", line 274, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2410, in load
    self.require(*args, **kwargs)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2433, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (billiard 3.6.0.0 (/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages), Requirement.parse('billiard<3.6.0,>=3.5.0.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/experimenter/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/_pytest/config/__init__.py", line 61, in main
    config = _prepareconfig(args, plugins)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/_pytest/config/__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/_pytest/config/__init__.py", line 655, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/_pytest/config/__init__.py", line 871, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/_pytest/config/__init__.py", line 817, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/pluggy/manager.py", line 280, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'celery' could not be loaded: (billiard 3.6.0.0 (/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages), Requirement.parse('billiard<3.6.0,>=3.5.0.2'))!
</details>

**Comment by peterbe** [comment]
It's a mystery to me how `master` can pass on CircleCI. Is it because there we use Python 3.6 and I use Python 3.7?

I can see how it *could* happen. 1) Two Dependabot PRs individually pass 2) each get merged in quick succession without being tested together. 
But in that scenario, the worst thing that can happen is that the last `master` fails in CI. But that's not happening here.

**Comment by peterbe** [comment]
Uh. If you, with the `master` branch as of today run `pip install -r app/requirements/default.txt` you get this error:

```
celery 4.2.1 has requirement billiard<3.6.0,>=3.5.0.2, but you'll have billiard 3.6.0.0 which is incompatible.
```
but the command succeeds. It's because it's a warning only. 

[What clumsy meathead approved an upgrade of billiard==3.6.0.0](https://github.com/mozilla/experimenter/pull/988)?
