### ISSUE TITLE
Intermittent test failure: test_get_live_experiments_in_previous_namespaces

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#10261]
Seen locally.  These lists should be ordered so not sure what we missed here?

```py
======================================================================
FAIL: test_get_live_experiments_in_previous_namespaces (experimenter.experiments.tests.test_models.TestNimbusExperiment.test_get_live_experiments_in_previous_namespaces)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/usr/local/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "/experimenter/experimenter/experiments/tests/test_models.py", line 2777, in test_get_live_experiments_in_previous_namespaces
    self.assertEqual(
  File "/usr/local/lib/python3.11/unittest/case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/case.py", line 1079, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
    ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/case.py", line 1061, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/lib/python3.11/unittest/case.py", line 703, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: Lists differ: ['realigned-user-facing-parallelism', 're-eng[83 chars]ity'] != ['re-engineered-user-facing-artificial-intell[83 chars]ity']

First differing element 0:
'realigned-user-facing-parallelism'
're-engineered-user-facing-artificial-intelligence'

- ['realigned-user-facing-parallelism',
-  're-engineered-user-facing-artificial-intelligence',
? ^

+ ['re-engineered-user-facing-artificial-intelligence',
? ^

+  'realigned-user-facing-parallelism',
   'right-sized-upward-trending-flexibility']
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4360)

**Comment by eliserichards** [comment]
This is strange 🤔 https://github.com/mozilla/experimenter/pull/10240 should have fixed this. Do you know if you'd pulled from `main` yet when you saw this error @jaredlockhart ?
