### ISSUE TITLE
Intermittent JS test failure

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2441]
I just saw this on circle:

```
The `DesignForm` component for generic › renders generic forms

    Found multiple elements with the display value: qui.

    (If this is intentional, then use the `*AllBy*` variant of the query (like `queryAllByText`, `getAllByText`, or `findAllByText`)).

    <body>
      <div>
        <div
          class="page-edit-design"
        >
          <div
            class="container"
          >
            <form
              id="design-form"
            >
              <div>
                <div
                  class="mb-3 row"
                >
                  <div
                    class="text-right col-md-2"
                  >
                    <label
                      class="form-label"
                    >
                      <strong>
                        Design
                      </strong>
                      <div
                        class="required-label required"
                      >
                        <div
                          class="text-danger"
                        >
                          Required
                        </div>
                      </div>
                    </label>
                    <div>
                      <div>
                        <a
                          href="#"
                          name="design"
                        >
                          Help
                        </a>
                      </div>
                    </div>
                  </div>
                  <div
                    class="col-md-10"
                  >
                    <textarea
                      class="form-control"
                      data-testid="design"
                      name="design"
                      rows="10"
                      type="text"
                    >
                      Magnam qui eos accusantium. Non ducimus et praesentium vel pariatur ipsam ducimus labore aut. Labore autem necessitatibus cumque enim est rerum magnam. Omnis qui et necessitatibus ut dicta.
                    </textarea>
                    <div
                      class="text-muted collapse mt-2"
                    >
                      <div>
                        <p>
                          Specify the design of the experiment.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <hr
                  class="heavy-line my-5"
                />
                <div
                  data-testid="branch0"
                  id="control-branch-group"
                >
                  <div
                    class="mb-3 row"
                  >
                    <div
                      class="col-md-4 offset-md-2"
                    >
                      <h4>
                        Control Branch
                      </h4>
                    </div>
                    <div
                      class="text-right col-md-6"
                    />
                  </div>
                  <div
                    class="mb-3 row"
                  >
                    <div
                      class="text-right col-md-2"
                    >
                      <label
                        class="form-label"
                        for="variants-0-ratio"
                      >
                        <strong>
                          Branch Size
                        </strong>
                        <div
                          class="required-label required"
                        >
                          <div
                            class="text-danger"
                          >
                            Required
                          </div>
                        </div>
                      </label>
                      <div>
                        <div>
                          <a
                            href="#"
                            name="variants[0][ratio]"
                          >
                            Help
                          </a>
                        </div>
                      </div>
                    </div>
                    <div
                      class="col-md-10"
                    >
                      <input
                        class="form-control"
                        data-testid="Branch Size"
                        id="variants-0-ratio"
                        name="variants[0][ratio]"
                        type="text"
                        value="91"
                      />
                      <div
                        class="text-muted collapse mt-2"
                      >
                        <div>
                          <p>
                            Choose the size of this branch represented as a whole number. The size of all branches together must be equal to 100. It does not have to be exact, so these sizes are simply a recommendation of the relative distribution of the branches.
                          </p>
                          <p>
                            <strong>
                              Example:
                            </strong>
                             50
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    class="mb-3 row"
                  >
                    <div
                      class="text-right col-md-2"
                    >
                      <label
                        class="form-label"
                        for="variants-0-name"
                      >
                        <strong>
                          Name
                        </strong>
                        <div
                          class="required-label required"...

      69 | 
      70 |     for (let variant of successResponse.variants) {
    > 71 |       expect(getByDisplayValue(variant.name)).toBeInTheDocument();
         |              ^
      72 |       expect(getByDisplayValue(variant.description)).toBeInTheDocument();
      73 |       getAllByDisplayValue(variant.ratio).map(e =>
      74 |         expect(e).toBeInTheDocument(),

      at Object.getElementError (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/config.js:34:12)
      at getMultipleElementsFoundError (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:21:35)
      at getByDisplayValue (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:57:13)
      at Object.<anonymous> (experimenter/static/js/tests/GenericForm.test.js:71:14)
```

I haven't seen any of our js tests intermittently fail before, this same test suite passed during the PR run:

https://circleci.com/gh/mozilla/experimenter/9633

but failed during the build and deploy run:

https://circleci.com/gh/mozilla/experimenter/9636

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-152)

**Comment by jaredlockhart** [comment]
Probably a faker data collision.

**Comment by jaredlockhart** [comment]
This keeps happening to me, let's actually fix this.
