### ISSUE TITLE
Storybook Publishing fails for PRs based on forks of mozilla/experimenter

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3671]
Error: github.token: must be of type String
gcp.bucket: must be of type String
gcp.projectId: must be of type String
gcp.clientEmail: must be of type String
gcp.privateKey: must be of type String
 at Object.validate (/root/.npm/_npx/6/lib/node_modules/storybook-gcp-publisher/node_modules/convict/src/main.js:669:17)
 at loadConfig (/root/.npm/_npx/6/lib/node_modules/storybook-gcp-publisher/lib/config.js:265:10)
 at initContext (/root/.npm/_npx/6/lib/node_modules/storybook-gcp-publisher/index.js:39:24)
 at async main (/root/.npm/_npx/6/lib/node_modules/storybook-gcp-publisher/index.js:14:19)
Makefile:91: recipe for target 'publish_storybooks' failed
make: *** [publish_storybooks] Error 1

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-448)
┆Issue Number: EXP-448

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

PR in question is https://github.com/mozilla/experimenter/pull/3667/files

Failure is not intermittent - this failure will occur on any PR based on a fork of the upstream repo. Need to only run Storybook publishing for branches of mozilla/experimenter repo because the environment variable secrets are censored from forks.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Made a quick tweak to mozilla-fxa/storybook-gcp-publisher: If the env vars with credentials are missing in CircleCI, the Storybook build should exit without raising an error in exit status. So, worst case should be that the build is just skipped for PRs submitted from forks.

https://github.com/mozilla-fxa/storybook-gcp-publisher/commit/037e21538ae7914e6a136c8c018e396c65c089f5
