### ISSUE TITLE
Intermittent frontend test:   AppLayoutWithExperiment › polling › polls useExperiment when the prop is passed in

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4489]
```
Summary of all failing tests
FAIL src/components/AppLayoutWithExperiment/index.test.tsx
  ● AppLayoutWithExperiment › polling › polls useExperiment when the prop is passed in

    TestingLibraryElementError: Unable to find an element by: [data-testid="header-experiment-status-active"]

    <body>
      <div>
        <div
          style="outline: none;"
          tabindex="-1"
        >
          <div
            props="[object Object]"
          >
            <main
              class="h-100 pt-5 container-fluid"
              data-testid="page-loading"
            >
              <div
                class="h-100 container-lg mx-auto"
              >
                <div
                  class="text-center"
                >
                  <div
                    class="spinner-border text-primary"
                    data-testid="spinner"
                    role="status"
                  >
                    <span
                      class="sr-only"
                    >
                      Loading...
                    </span>
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>
    </body>

    <html>
      <head />
      <body>
        <div>
          <div
            style="outline: none;"
            tabindex="-1"
          >
            <div
              props="[object Object]"
            >
              <div
                class="h-100vh container-fluid"
                data-testid="AppLayoutWithSidebar"
              >
                <div
                  class="h-md-100 row"
                >
                  <div
                    class="bg-light pt-2 border-right shadow-sm col-xl-2 col-lg-3 col-md-3"
                  >
                    <nav
                      class="navbar"
                      data-testid="nav-sidebar"
                    >
                      <ul
                        class="flex-column font-weight-semibold nav"
                      >
                        <li
                          class="mx-1 my-2 mb-3 small font-weight-bold nav-item"
                        >
                          <a
                            class="text-secondary d-flex align-items-center"
                            data-sb-kind="pages/Home"
                            data-testid="nav-home"
                            href="/nimbus"
                          >
                            <svg
                              class="ml-n1"
                              height="18"
                              width="18"
                            >
                              chevron-left.svg
                            </svg>
                            Experiments
                          </a>
                        </li>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/EditOverview"
                            data-testid="nav-edit-overview"
                            href="/nimbus/demo-slug/edit/overview"
                          >
                            <svg
                              class="sidebar-icon"
                            >
                              cog.svg
                            </svg>
                            Overview
                          </a>
                        </li>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/EditBranches"
                            data-testid="nav-edit-branches"
                            href="/nimbus/demo-slug/edit/branches"
                          >
                            <svg
                              class="sidebar-icon"
                            >
                              layers.svg
                            </svg>
                            Branches
                          </a>
                        </li>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/EditMetrics"
                            data-testid="nav-edit-metrics"
                            href="/nimbus/demo-slug/edit/metrics"
                          >
                            <svg
                              class="sidebar-icon"
                            >
                              chart-arrow.svg
                            </svg>
                            Metrics
                          </a>
                        </li>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/EditAudience"
                            data-testid="nav-edit-audience"
                            href="/nimbus/demo-slug/edit/audience"
                          >
                            <svg
                              class="sidebar-icon"
                            >
                              person.svg
                            </svg>
                            Audience
                          </a>
                        </li>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/RequestReview"
                            data-testid="nav-request-review"
                            href="/nimbus/demo-slug/request-review"
                          >
                            <svg
                              class="sidebar-icon"
                            >
                              clipboard.svg
                            </svg>
                            Review & Launch
                          </a>
                        </li>
                      </ul>
                    </nav>
                  </div>
                  <div
                    class="ml-auto mr-auto col-md-9 col-xl-10 pt-5 px-md-3 px-lg-5 col"
                  >
                    <main
                      class="container-lg mx-auto"
                    >
                      <section
                        data-testid="AppLayoutWithExperiment"
                      >
                        <header
                          class="border-bottom"
                          data-testid="header-experiment"
                        >
                          <h1
                            class="h5 font-weight-normal"
                            data-testid="header-experiment-name"
                          >
                            Open-architected background installation
                          </h1>
                          <p
                            class="text-monospace text-secondary mb-1 small"
                            data-testid="header-experiment-slug"
                          >
                            demo-slug
                          </p>
                          <div
                            class="row"
                          >
                            <div
                              class="col"
                            >
                              <p
                                class="header-experiment-status position-relative mt-2 d-inline-block"
                              >
                                <span
                                  class="border rounded-pill px-2 bg-white position-relative border-primary text-primary mr-3"
                                  data-testid="header-experiment-status-active"
                                >
                                  Draft
                                </span>
                                <span
                                  class="border rounded-pill px-2 bg-white position-relative border-muted text-muted mr-3"
                                  data-testid="header-experiment-status"
                                >
                                  Review
                                </span>
                                <span
                                  class="border rounded-pill px-2 bg-white position-relative border-muted text-muted mr-3"
                                  data-testid="header-experiment-status"
                                >
                                  Live
                                </span>
                                <span
                                  class="border rounded-pill px-2 bg-white position-relative border-muted text-muted"
                                  data-testid="header-experiment-status"
                                >
                                  Complete
                                </span>
                              </p>
                            </div>
                          </div>
                        </header>
                        <h2
                          class="mt-3 mb-4 h4"
                          data-testid="page-title"
                        >
                          Howdy!
                        </h2>
                        <div
                          class="my-4"
                        >
                          <p
                            data-testid="child"
                          >
                            demo-slug
                          </p>
                        </div>
                      </section>
                    </main>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>Error: Unable to find an element by: [data-testid="header-experiment-status-active"]

    <body>
      <div>
        <div
          style="outline: none;"
          tabindex="-1"
        >
          <div
            props="[object Object]"
          >
            <main
              class="h-100 pt-5 container-fluid"
              data-testid="page-loading"
            >
              <div
                class="h-100 container-lg mx-auto"
              >
                <div
                  class="text-center"
                >
                  <div
                    class="spinner-border text-primary"
                    data-testid="spinner"
                    role="status"
                  >
                    <span
                      class="sr-only"
                    >
                      Loading...
                    </span>
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>
    </body>

      60 |     it("polls useExperiment when the prop is passed in", async () => {
      61 |       render(<Subject mocks={[mock, updatedMock]} polling />);
    > 62 |       await waitFor(() => {
         |             ^
      63 |         expect(
      64 |           screen.getByTestId("header-experiment-status-active"),
      65 |         ).toHaveTextContent("Draft");

      at waitForWrapper (../../node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at Object.<anonymous> (src/components/AppLayoutWithExperiment/index.test.tsx:62:13)


Test Suites: 1 failed, 52 passed, 53 total
Tests:       1 failed, 336 passed, 337 total
Snapshots:   0 total
Time:        20.547s
Ran all test suites.
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-878)
┆Issue Number: EXP-878

**Comment by jaredlockhart** [comment]
Haven't seen this in a while, closing until we see again.
