### ISSUE TITLE
Intermittent test failure: PageNew › handles experiment form submission with server API error

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4790]
Seen locally.

```
FAIL src/components/PageNew/index.test.tsx
  ● PageNew › handles experiment form submission with server API error

    expect(element).toHaveTextContent()

    Expected element to have text content:
      {"*":"Sorry, an error occurred while submitting. Please try again."}
    Received:
      {}

      82 |       fireEvent.click(screen.getByTestId("submit"));
      83 |     });
    > 84 |     expect(screen.getByTestId("submitErrors")).toHaveTextContent(
         |                                                ^
      85 |       JSON.stringify({ "*": SUBMIT_ERROR }),
      86 |     );
      87 |   });

      at Object.<anonymous> (src/components/PageNew/index.test.tsx:84:48)
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1050)
┆Issue Number: EXP-1050

**Comment by jaredlockhart** [comment]
@jodyheavener Just hit this again locally with your patch:

```
FAIL src/components/PageNew/index.test.tsx
  ● PageNew › handles experiment form submission

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: "foo-bar-baz/edit/overview"

    Number of calls: 0

      53 |       fireEvent.click(screen.getByTestId("submit"));
      54 |     });
    > 55 |     expect(navigate).toHaveBeenCalledWith("foo-bar-baz/edit/overview");
         |                      ^
      56 |   });
      57 |
      58 |   it("handles experiment form submission with server-side validation errors", async () => {

      at Object.<anonymous> (src/components/PageNew/index.test.tsx:55:22)
``` 

😿

**Comment by jodyheavener** [comment]
This is a different test and I suspect applying my other change to it will fix it. Will PR shortly.

**Comment by jaredlockhart** [comment]
oh oh oh it's a new failure i'll file a new ticket then i didn't look at the test name derp

**Comment by jaredlockhart** [comment]
Filed https://github.com/mozilla/experimenter/issues/4941
