### ISSUE TITLE
Intermittent test failure: hooks/useChangeOperationMutation › can successfully execute mutation set callbacks

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#5988]
Seen locally

```
Summary of all failing tests
FAIL src/hooks/useChangeOperationMutation.test.tsx
  ● hooks/useChangeOperationMutation › can successfully execute mutation set callbacks

    Timed out in waitForNextUpdate after 1000ms.

      26 |       invokeCallback(idx);
      27 |
    > 28 |       await waitForNextUpdate();
         |       ^
      29 |       expect(result.current.isLoading).toBeTruthy();
      30 |
      31 |       await waitForNextUpdate();

      at waitForNextUpdate (../../node_modules/@testing-library/react-hooks/lib/core/asyncUtils.js:102:13)
      at Object.<anonymous> (src/hooks/useChangeOperationMutation.test.tsx:28:7)
```

**Comment by lmorchard** [comment]
Hmm, that code was introduced by me [in PR 5852](https://github.com/mozilla/experimenter/commit/26ead8a0d4ce5aad11b9e031131c336cfe607170#diff-b1dfec43d2d9c2af62a3975eefe2e830fb2538f75347450b2f309cd9d80397eaR26-R29), but I hadn't seen that particular line fail locally. I can bang on it for a bit and see what's up. It's probably relatively safe to disable if it happens a bunch, though, since the basic functionality is also exercised in the other tests in that suite.
