### ISSUE TITLE
Intermittent test failure in TimelinePopForm

### ISSUE THREAD

**Issue by dmose** [mozilla/experimenter#6284]
```
FAIL js/tests/TimelinePopForm.test.js (77.389 s)
  The TimelinePopForm component for experiments
    ✓ displays and edits timeline and population data (16008 ms)
    ✕ displays errors on firefox version errors (7275 ms)
    ✓ logs failure of api call (129 ms)
    ✓ displays and edit rollout playbook on rollout delivery (3530 ms)

  ● The TimelinePopForm component for experiments › displays errors on firefox version errors

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      129 |   });
      130 |
    > 131 |   it("displays errors on firefox version errors", async () => {
          |   ^
      132 |     rejectedSetUp();
      133 |
      134 |     let scrollIntoViewMock = jest.fn();

      at new Spec (../../../node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (js/tests/TimelinePopForm.test.js:131:3)
      at Object.<anonymous> (js/tests/TimelinePopForm.test.js:14:1)
```

**Comment by dmose** [comment]
I seem to hit it quite frequently.  Possibly of note is that I'm using a fully dockerized setup on Mac.

**Comment by jaredlockhart** [comment]
Yep this one is still a problem.
