### ISSUE TITLE
Intermittent test failure:  redirects from ':slug/edit' to ':slug/edit/overview'

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6374]
Seen in https://app.circleci.com/pipelines/github/mozilla/experimenter/11061/workflows/d2568fcc-2299-4c8d-a984-8ad871bb7e7a/jobs/33277

```html
FAIL src/components/App/index.test.tsx
  ● App › :slug routes › redirects from ':slug/edit' to ':slug/edit/overview'

    TestingLibraryElementError: Unable to find an element by: [data-testid="PageEditOverview"]

    <body>
      <div>
        <div
          style="outline: none;"
          tabindex="-1"
        >
          <div
            style="outline: none;"
            tabindex="-1"
          >
            <main
              class="h-100 pt-5 container-fluid"
              data-testid="page-loading"
              id="page-loading-page"
            >
              <div
                class="h-100 container-lg mx-auto"
              >
                <div
                  class="text-center"
                >
                  <div
                    class="spinner-border text-primary"
                    data-testid="spinner"
                    role="status"
                  >
                    <span
                      class="sr-only"
                    >
                      Loading...
                    </span>
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>
    </body>

    <html>
      <head>
        <style
          data-react-tooltip="true"
        >
          .__react_component_tooltip {
      border-radius: 3px;
      display: inline-block;
      font-size: 13px;
      left: -999em;
      opacity: 0;
      padding: 8px 21px;
      position: fixed;
      pointer-events: none;
      transition: opacity 0.3s ease-out;
      top: -999em;
      visibility: hidden;
      z-index: 999;
    }
    .__react_component_tooltip.allow_hover, .__react_component_tooltip.allow_click {
      pointer-events: auto;
    }
    .__react_component_tooltip::before, .__react_component_tooltip::after {
      content: "";
      width: 0;
      height: 0;
      position: absolute;
    }
    .__react_component_tooltip.show {
      opacity: 0.9;
      margin-top: 0;
      margin-left: 0;
      visibility: visible;
    }
    .__react_component_tooltip.place-top::before {
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
      bottom: -8px;
      left: 50%;
      margin-left: -10px;
    }
    .__react_component_tooltip.place-bottom::before {
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
      top: -8px;
      left: 50%;
      margin-left: -10px;
    }
    .__react_component_tooltip.place-left::before {
      border-top: 6px solid transparent;
      border-bottom: 6px solid transparent;
      right: -8px;
      top: 50%;
      margin-top: -5px;
    }
    .__react_component_tooltip.place-right::before {
      border-top: 6px solid transparent;
      border-bottom: 6px solid transparent;
      left: -8px;
      top: 50%;
      margin-top: -5px;
    }
    .__react_component_tooltip .multi-line {
      display: block;
      padding: 2px 0;
      text-align: center;
    }
        </style>
        <title>
          Open-architected background installation – Overview | Experimenter
        </title>
      </head>
      <body>
        <div>
          <div
            style="outline: none;"
            tabindex="-1"
          >
            <div
              style="outline: none;"
              tabindex="-1"
            >
              <div
                class="h-100vh container-fluid"
                data-testid="AppLayoutWithSidebar"
              >
                <div
                  class="h-md-100 row"
                >
                  <div
                    class="bg-light pt-2 border-right shadow-sm col-xl-2 col-lg-3 col-md-3"
                  >
                    <nav
                      class="navbar"
                      data-testid="nav-sidebar"
                    >
                      <ul
                        class="flex-column font-weight-semibold w-100 nav"
                      >
                        <li
                          class="mb-3 small font-weight-bold nav-item"
                        >
                          <a
                            class="text-secondary d-flex align-items-center"
                            data-sb-kind="pages/Home"
                            data-testid="nav-home"
                            href="/nimbus"
                          >
                            <svg
                              class="ml-n1"
                              height="18"
                              width="18"
                            >
                              chevron-left.svg
                            </svg>
                            Back to Experiments
                          </a>
                        </li>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/Summary"
                            data-testid="nav-summary"
                            href="/nimbus/my-special-slug"
                          >
                            <svg
                              class="sidebar-icon align-self-start mt-1"
                            >
                              airplane.svg
                            </svg>
                            <span>
                              <span>
                                Summary
                              </span>
                              <span
                                class="d-block small"
                              >
                                Request Launch
                              </span>
                            </span>
                          </a>
                        </li>
                        <p
                          class="edit-divider position-relative small my-2"
                        >
                          <span
                            class="position-relative bg-light pl-1 pr-2 text-muted"
                          >
                            Edit
                          </span>
                        </p>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/EditOverview"
                            data-testid="nav-edit-overview"
                            href="/nimbus/my-special-slug/edit/overview"
                          >
                            <svg
                              class="sidebar-icon"
                            >
                              cog.svg
                            </svg>
                            Overview
                          </a>
                        </li>
                        <li
                          class="mx-1 my-2 nav-item"
                        >
                          <a
                            class="text-dark d-flex align-items-center"
                            data-sb-kind="pages/EditBranches"
                            data-testid="nav-edit-branches"
                            href="/nimbus/my-special-slug/edit/branches"
                          >
                            <svg
       ...Error: Unable to find an element by: [data-testid="PageEditOverview"]

    <body>
      <div>
        <div
          style="outline: none;"
          tabindex="-1"
        >
          <div
            style="outline: none;"
            tabindex="-1"
          >
            <main
              class="h-100 pt-5 container-fluid"
              data-testid="page-loading"
              id="page-loading-page"
            >
              <div
                class="h-100 container-lg mx-auto"
              >
                <div
                  class="text-center"
                >
                  <div
                    class="spinner-border text-primary"
                    data-testid="spinner"
                    role="status"
                  >
                    <span
                      class="sr-only"
                    >
                      Loading...
                    </span>
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>
    </body>

      84 |
      85 |       // waitFor the redirect
    > 86 |       await waitFor(() => {
         |             ^
      87 |         expect(screen.getByTestId("PageEditOverview")).toBeInTheDocument();
      88 |       });
      89 |     });

      at waitForWrapper (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at Object.<anonymous> (src/components/App/index.test.tsx:86:13)


Test Suites: 1 failed, 74 passed, 75 total
Tests:       1 failed, 490 passed, 491 total
Snapshots:   0 total
Time:        143.187s
Ran all test suites.
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed.
Exit code: 1
Command: /root/.nvm/versions/node/v14.17.1/bin/node
Arguments: /usr/share/yarn/lib/cli.js test:cov
Directory: /app/experimenter/nimbus-ui
Output:

parallel: This job failed:
CI=yes yarn workspace @experimenter/nimbus-ui test:cov
-------------------------------------------------
Some Checks Failed
-------------------------------------------------

ERROR: 1
make: *** [Makefile:103: check] Error 1

Exited with code exit status 2

```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1731)

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

FWIW, just saw another failure on main branch from this:

https://app.circleci.com/pipelines/github/mozilla/experimenter/11251/workflows/275c5eb2-edd8-443f-b321-651e48937b3e/jobs/33996 ( https://app.circleci.com/pipelines/github/mozilla/experimenter/11251/workflows/275c5eb2-edd8-443f-b321-651e48937b3e/jobs/33996 )

**Comment by jaredlockhart** [comment]
This is fixed now by refactors from @lmorchard 🙏
