### ISSUE TITLE
Intermittent test failure: PageHome

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6397]
Just saw this locally:

```
FAIL src/components/PageHome/index.test.tsx (11.16s)
  ● Console

    console.error ../../node_modules/@testing-library/react-hooks/lib/core/console.js:19
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

  ● PageHome › supports updating search params when tabs are clicked

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      64 |   });
      65 |
    > 66 |   it("supports updating search params when tabs are clicked", async () => {
         |   ^
      67 |     await renderAndWaitForLoaded();
      68 |     for (const [tabKey, tab] of findTabs()) {
      69 |       fireEvent.click(tab);

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/components/PageHome/index.test.tsx:66:3)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:25:1)

  ● PageHome › renders the error warning and refetches when an error occurs querying experiments

    Changed from using real timers to fake timers while using waitFor. This is not allowed and will result in very strange behavior. Please ensure you're awaiting all async things your test is doing before changing to fake timers. For more info, please go to https://github.com/testing-library/dom-testing-library/issues/830

      68 |     for (const [tabKey, tab] of findTabs()) {
      69 |       fireEvent.click(tab);
    > 70 |       await waitFor(() => {
         |             ^
      71 |         expect(tab).toHaveClass("active");
      72 |         expect(screen.getByTestId("location")).toHaveTextContent(
      73 |           `tab=${tabKey}`,

      at waitForWrapper (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:70:13)

PASS src/components/PageSummary/index.test.tsx (33.547s)
PASS src/components/PageResults/index.test.tsx (20.606s)

Summary of all failing tests
FAIL src/components/PageHome/index.test.tsx (11.16s)
  ● PageHome › supports updating search params when tabs are clicked

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      64 |   });
      65 |
    > 66 |   it("supports updating search params when tabs are clicked", async () => {
         |   ^
      67 |     await renderAndWaitForLoaded();
      68 |     for (const [tabKey, tab] of findTabs()) {
      69 |       fireEvent.click(tab);

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/components/PageHome/index.test.tsx:66:3)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:25:1)

  ● PageHome › renders the error warning and refetches when an error occurs querying experiments

    Changed from using real timers to fake timers while using waitFor. This is not allowed and will result in very strange behavior. Please ensure you're awaiting all async things your test is doing before changing to fake timers. For more info, please go to https://github.com/testing-library/dom-testing-library/issues/830

      68 |     for (const [tabKey, tab] of findTabs()) {
      69 |       fireEvent.click(tab);
    > 70 |       await waitFor(() => {
         |             ^
      71 |         expect(tab).toHaveClass("active");
      72 |         expect(screen.getByTestId("location")).toHaveTextContent(
      73 |           `tab=${tabKey}`,

      at waitForWrapper (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:70:13)
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1747)

**Comment by jaredlockhart** [comment]
This is still an issue.
