### ISSUE TITLE
Intermittent test failure: renders the error warning when an error occurs polling the experiment

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6656]
Seen in https://app.circleci.com/pipelines/github/mozilla/experimenter/11558/workflows/9a24763f-d30e-4a5e-96ba-416dee255640/jobs/35200

```
FAIL src/components/AppLayoutWithExperiment/index.test.tsx (16.187s)
  ● AppLayoutWithExperiment › polling › renders the error warning when an error occurs polling the experiment

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

       95 |     });
       96 |
    >  97 |     it("renders the error warning when an error occurs polling the experiment", async () => {
          |     ^
       98 |       const mockWithError = { ...initialMock, error: new Error("boop") };
       99 |       render(
      100 |         <Subject mocks={[initialMock, mockWithError, updatedMock]} polling />,

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/components/AppLayoutWithExperiment/index.test.tsx:97:5)
      at Suite.<anonymous> (src/components/AppLayoutWithExperiment/index.test.tsx:56:3)
      at Object.<anonymous> (src/components/AppLayoutWithExperiment/index.test.tsx:16:1)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1876)

**Comment by jaredlockhart** [comment]
Closing as dupe of https://github.com/mozilla/experimenter/issues/6720
