### ISSUE TITLE
Intermittent test failure: PageSummary › handles submission with server-side validation errors

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6802]
Seen in https://app.circleci.com/pipelines/github/mozilla/experimenter/11798/workflows/051d016a-cb1f-4e93-8a24-00c390fe8132/jobs/36117

```js
FAIL src/components/PageSummary/index.test.tsx (43.059s)
  ● PageSummary › handles submission with server-side validation errors

    TestingLibraryElementError: Unable to find an element by: [data-testid="submit-error"]

    <body>
      <div>
        <div
          style="outline: none;"
          tabindex="-1"
        >
          <div
            props="[object Object]"
          >
            <div
              class="fade alert alert-danger show"
              data-testid="apollo-error-alert"
              role="alert"
            >
              <div
                class="alert-heading h4"
              >
                Network Error
              </div>
              <p
                class="mb-6"
              >
                Something went wrong. Please try again later.
              </p>
              <hr />
              <p>
                <b>
                  Message:
                </b>
                 
                No more mocked responses for the query: query getExperiment($slug: String!) {
      experimentBySlug(slug: $slug) {
        id
        isRollout
        isArchived
        canEdit
        canArchive
        name
        slug
        status
        statusNext
        publishStatus
        monitoringDashboardUrl
        resultsReady
        hypothesis
        application
        publicDescription
        conclusionRecommendation
        takeawaysSummary
        owner {
          email
          __typename
        }
        parent {
          name
          slug
          __typename
        }
        warnFeatureSchema
        referenceBranch {
          id
          name
          slug
          description
          ratio
          featureValue
          featureEnabled
          screenshots {
            id
            description
            image
            __typename
          }
          __typename
        }
        treatmentBranches {
          id
          name
          slug
          description
          ratio
          featureValue
          featureEnabled
          screenshots {
            id
            description
            image
            __typename
          }
          __typename
        }
        featureConfig {
          id
          slug
          name
          description
          application
          ownerEmail
          schema
          __typename
        }
        primaryOutcomes
        secondaryOutcomes
        channel
        firefoxMinVersion
        targetingConfigSlug
        jexlTargetingExpression
        populationPercent
        totalEnrolledClients
        proposedEnrollment
        proposedDuration
        readyForReview {
          ready
          message
          warnings
          __typename
        }
        startDate
        computedEndDate
        computedEnrollmentDays
        computedDurationDays
        riskMitigationLink
        riskRevenue
        riskBrand
        riskPartnerRelated
        signoffRecommendations {
          qaSignoff
          vpSignoff
          legalSignoff
          __typename
        }
        documentationLinks {
          title
          link
          __typename
        }
        isEnrollmentPausePending
        isEnrollmentPaused
        enrollmentEndDate
        canReview
        reviewRequest {
          changedOn
          changedBy {
            email
            __typename
          }
          __typename
        }
        rejection {
          message
          oldStatus
          oldStatusNext
          changedOn
          changedBy {
            email
            __typename
          }
          __typename
        }
        timeout {
          changedOn
          changedBy {
            email
            __typename
          }
          __typename
        }
        recipeJson
        reviewUrl
        locales {
          id
          name
          __typename
        }
        countries {
          id
          name
          __typename
        }
        __typename
      }
    }
    , variables: {"slug":"demo-slug"}
              </p>
            </div>
          </div>
        </div>
      </div>
    </body>

    <html>
      <head>
        <style
          data-react-tooltip="true"
        >
          .__react_component_tooltip {
      border-radius: 3px;
      display: inline-block;
      font-size: 13px;
      left: -999em;
      opacity: 0;
      padding: 8px 21px;
      position: fixed;
      pointer-events: none;
      transition: opacity 0.3s ease-out;
      top: -999em;
      visibility: hidden;
      z-index: 999;
    }
    .__react_component_tooltip.allow_hover, .__react_component_tooltip.allow_click {
      pointer-events: auto;
    }
    .__react_component_tooltip::before, .__react_component_tooltip::after {
      content: "";
      width: 0;
      height: 0;
      position: absolute;
    }
    .__react_component_tooltip.show {
      opacity: 0.9;
      margin-top: 0;
      margin-left: 0;
      visibility: visible;
    }
    .__react_component_tooltip.place-top::before {
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
      bottom: -8px;
      left: 50%;
      margin-left: -10px;
    }
    .__react_component_tooltip.place-bottom::before {
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
      top: -8px;
      left: 50%;
      margin-left: -10px;
    }
    .__react_component_tooltip.place-left::before {
      border-top: 6px solid transparent;
      border-bottom: 6px solid transparent;
      right: -8px;
      top: 50%;
      margin-top: -5px;
    }
    .__react_component_tooltip.place-right::before {
      border-top: 6px solid transparent;
      border-bottom: 6px solid transparent;
      left: -8px;
      top: 50%;
      margin-top: -5px;
    }
    .__react_component_tooltip .multi-line {
      display: block;
      padding: 2px 0;
      text-align: center;
    }
        </style>
        <title>
          Open-architected background installation – Summary, Request Launch | Experimenter
        </title>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-2b097c-container{position:relative;box-sizing:border-box;}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-2b097c-container direction{}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-2b097c-container pointerEvents{}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-1f43avz-a11yText-A11yText{z-index:9999;border:0;clip:rect(1px, 1px, 1px, 1px);height:1px;width:1px;position:absolute;overflow:hidden;padding:0;white-space:nowrap;}/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIkExMXlUZXh0LmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQVFJIiwiZmlsZSI6IkExMXlUZXh0LmpzIiwic291cmNlc0NvbnRlbnQiOlsiLy8gQGZsb3dcbi8qKiBAanN4IGpzeCAqL1xuaW1wb3J0IHsgdHlwZSBFbGVtZW50Q29uZmlnIH0gZnJvbSAncmVhY3QnO1xuaW1wb3J0IHsganN4IH0gZnJvbSAnQGVtb3Rpb24vcmVhY3QnO1xuXG4vLyBBc3Npc3RpdmUgdGV4dCB0byBkZXNjcmliZSB2aXN1YWwgZWxlbWVudHMuIEhpZGRlbiBmb3Igc2lnaHRlZCB1c2Vycy5cbmNvbnN0IEExMXlUZXh0ID0gKHByb3BzOiBFbGVtZW50Q29uZmlnPCdzcGFuJz4pID0+IChcbiAgPHNwYW5cbiAgICBjc3M9e3tcbiAgICAgIGxhYmVsOiAnYTExeVRleHQnLFxuICAgICAgekluZGV4OiA5OTk5LFxuICAgICAgYm9yZGVyOiAwLFxuICAgICAgY2xpcDogJ3JlY3QoMXB4LCAxcHgsIDFweCwgMXB4KScsXG4gICAgICBoZWlnaHQ6IDEsXG4gICAgICB3aWR0aDogMSxcbiAgICAgIHBvc2l0aW9uOiAnYWJzb2x1dGUnLFxuICAgICAgb3ZlcmZsb3c6ICdoaWRkZW4nLFxuICAgICAgcGFkZGluZzogMCxcbiAgICAgIHdoaXRlU3BhY2U6ICdub3dyYXAnLFxuICAgIH19XG4gICAgey4uLnByb3BzfVxuICAvPlxuKTtcblxuZXhwb3J0IGRlZmF1bHQgQTExeVRleHQ7XG4iXX0= */
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-yk16xz-control{-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;background-color:hsl(0, 0%, 100%);border-color:hsl(0, 0%, 80%);border-radius:4px;border-style:solid;border-width:1px;cursor:default;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-flex-wrap:wrap;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-box-pack:justify;-webkit-justify-content:space-between;justify-content:space-between;min-height:38px;outline:0!important;position:relative;-webkit-transition:all 100ms;transition:all 100ms;box-sizing:border-box;}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-yk16xz-control boxShadow{}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-yk16xz-control:hover{border-color:hsl(0, 0%, 70%);}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-g1d714-ValueContainer{-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex:1;-ms-flex:1;flex:1;-webkit-box-flex-wrap:wrap;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;padding:2px 8px;-webkit-overflow-scrolling:touch;position:relative;overflow:hidden;box-sizing:border-box;}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-1uccc91-singleValue{color:hsl(0, 0%, 20%);margin-left:2px;margin-right:2px;max-width:calc(100% - 8px);overflow:hidden;position:absolute;text-overflow:ellipsis;white-space:nowrap;top:50%;-webkit-transform:translateY(-50%);-moz-transform:translateY(-50%);-ms-transform:translateY(-50%);transform:translateY(-50%);box-sizing:border-box;}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-b8ldur-Input{margin:2px;padding-bottom:2px;padding-top:2px;visibility:visible;color:hsl(0, 0%, 20%);box-sizing:border-box;}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-1hb7zxy-IndicatorsContainer{-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-align-self:stretch;-ms-flex-item-align:stretch;align-self:stretch;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-shrink:0;-ms-flex-negative:0;flex-shrink:0;box-sizing:border-box;}
        </style>
        <style
          data-emotion="css"
          data-s=""
        >
          
          .css-1oke...Error: Unable to find an element by: [data-testid="submit-error"]

    <body>
      <div>
        <div
          style="outline: none;"
          tabindex="-1"
        >
          <div
            props="[object Object]"
          >
            <div
              class="fade alert alert-danger show"
              data-testid="apollo-error-alert"
              role="alert"
            >
              <div
                class="alert-heading h4"
              >
                Network Error
              </div>
              <p
                class="mb-6"
              >
                Something went wrong. Please try again later.
              </p>
              <hr />
              <p>
                <b>
                  Message:
                </b>
                 
                No more mocked responses for the query: query getExperiment($slug: String!) {
      experimentBySlug(slug: $slug) {
        id
        isRollout
        isArchived
        canEdit
        canArchive
        name
        slug
        status
        statusNext
        publishStatus
        monitoringDashboardUrl
        resultsReady
        hypothesis
        application
        publicDescription
        conclusionRecommendation
        takeawaysSummary
        owner {
          email
          __typename
        }
        parent {
          name
          slug
          __typename
        }
        warnFeatureSchema
        referenceBranch {
          id
          name
          slug
          description
          ratio
          featureValue
          featureEnabled
          screenshots {
            id
            description
            image
            __typename
          }
          __typename
        }
        treatmentBranches {
          id
          name
          slug
          description
          ratio
          featureValue
          featureEnabled
          screenshots {
            id
            description
            image
            __typename
          }
          __typename
        }
        featureConfig {
          id
          slug
          name
          description
          application
          ownerEmail
          schema
          __typename
        }
        primaryOutcomes
        secondaryOutcomes
        channel
        firefoxMinVersion
        targetingConfigSlug
        jexlTargetingExpression
        populationPercent
        totalEnrolledClients
        proposedEnrollment
        proposedDuration
        readyForReview {
          ready
          message
          warnings
          __typename
        }
        startDate
        computedEndDate
        computedEnrollmentDays
        computedDurationDays
        riskMitigationLink
        riskRevenue
        riskBrand
        riskPartnerRelated
        signoffRecommendations {
          qaSignoff
          vpSignoff
          legalSignoff
          __typename
        }
        documentationLinks {
          title
          link
          __typename
        }
        isEnrollmentPausePending
        isEnrollmentPaused
        enrollmentEndDate
        canReview
        reviewRequest {
          changedOn
          changedBy {
            email
            __typename
          }
          __typename
        }
        rejection {
          message
          oldStatus
          oldStatusNext
          changedOn
          changedBy {
            email
            __typename
          }
          __typename
        }
        timeout {
          changedOn
          changedBy {
            email
            __typename
          }
          __typename
        }
        recipeJson
        reviewUrl
        locales {
          id
          name
          __typename
        }
        countries {
          id
          name
          __typename
        }
        __typename
      }
    }
    , variables: {"slug":"demo-slug"}
              </p>
            </div>
          </div>
        </div>
      </div>
    </body>

      335 |     render(<Subject mocks={[mock, mutationMock]} />);
      336 |     await launchFromDraftToReview();
    > 337 |     await waitFor(() => {
          |           ^
      338 |       expect(screen.getByTestId("submit-error")).toBeInTheDocument();
      339 |       expect(screen.getByTestId("submit-error")).toHaveTextContent(
      340 |         errorMessage,

      at waitForWrapper (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:173:27)
      at Object.<anonymous> (src/components/PageSummary/index.test.tsx:337:11)


Test Suites: 1 failed, 78 passed, 79 total
```

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1945)

**Comment by lmorchard** [comment]
Banged on this for awhile yesterday, but couldn't find anything obvious. Test code looks okay and very similar to neighboring tests. Passes for me locally, even after running it in a loop for an hour over lunch. [CI passed with a few reruns on a branch](https://app.circleci.com/pipelines/github/mozilla/experimenter?branch=6802-intermittent-pagesummary-failure&filter=all).

Not sure where to take this issue next without reproducing the failure.

**Comment by pdehaan** [comment]
This is semi-interesting (but no doubt :100: unrelated to anything) in the output:

```html
          <div
            props="[object Object]"
          >
```
