### ISSUE TITLE
Intermittent test failure: displays grouped metrics via onClick

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6818]
Seen in https://app.circleci.com/pipelines/github/mozilla/experimenter/11821/workflows/211f7e35-076b-46db-a642-19611c752ede/jobs/36206

```js
FAIL src/components/PageResults/index.test.tsx (54.442s)
  ● displays grouped metrics via onClick

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      101 | });
      102 |
    > 103 | it("displays grouped metrics via onClick", async () => {
          | ^
      104 |   mockExperiment = mockExperimentQuery("demo-slug").experiment;
      105 |   mockAnalysisData = mockAnalysis();
      106 |   render(<Subject />);

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (src/components/PageResults/index.test.tsx:103:1)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1956)

**Comment by jaredlockhart** [comment]
Closing as duplicate of https://github.com/mozilla/experimenter/issues/6397
