### ISSUE TITLE
[Sentry] Some users are already enrolled before they see a new experiment for the first time

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6889]
Sentry error popped up in Fenix 91, backtrace:
```
org.mozilla.experiments.nimbus.internal.NimbusErrorException$InternalError: Internal error: New experiment but enrollment already exists.
    at org.mozilla.experiments.nimbus.internal.NimbusError.intoException(nimbus.kt:9)
    at org.mozilla.experiments.nimbus.internal.NimbusClient.applyPendingExperiments(nimbus.kt:15)
    at org.mozilla.experiments.nimbus.-$$LambdaGroup$ks$FFGd6J-jWuYuF4BxN9FoSzJwXkw.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:4)
    at org.mozilla.experiments.nimbus.Nimbus.withCatchAll(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus.applyPendingExperimentsOnThisThread$nimbus_release(Nimbus.kt:1)
    at org.mozilla.experiments.nimbus.Nimbus$applyPendingExperiments$1.invokeSuspend(Nimbus.kt:2)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
```

Sentry report: https://sentry.prod.mozaws.net/operations/firefox/issues/12219507/ 

I'll take a quick look to see if I can point out where things are going wrong

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-2077)

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

A few thoughts after looking into this with Travis Long for a bit, the issue started on AS v79.0.0, which didn’t have any major Nimbus changes, although there was a slight change in the feature API work: https://github.com/mozilla/application-services/pull/4058 ( https://github.com/mozilla/application-services/pull/4058|smart-link ) 

In the meantime, we closed a couple of old experiments that might have been causing this, we’ll monitor the numbers and see if they go down.

Regardless, we should add some better error handling for this case - the case where there is a new experiment that somehow the user already has an enrollment for. An example of what we can do is wipe the old enrollment which is almost guaranteed to be an indicator of WasEnrolled anyways.

**Comment by data-sync-user** [comment]
➤ Tarik Eshaq commented:

I’m going to drop this back to the backlog since I don’t think we’ll work on it this sprint and after removing the old experiments, the numbers died down.
