### ISSUE TITLE
Error loading feature: major release 2022

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#7595]
Just saw this locally, it's not causing any blocking errors, but it will prevent the schema from being up to date.

```
INFO 2022-08-15 17:40:12,358 root Feature Loaded: firefox-desktop/glean
Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/experimenter/features/management/commands/load_feature_configs.py", line 26, in handle
    if (schema := feature.get_jsonschema()) is not None:
  File "/app/experimenter/features/__init__.py", line 87, in get_jsonschema
    return self.generate_jsonschema()
  File "/app/experimenter/features/__init__.py", line 69, in generate_jsonschema
    for variable_slug, variable in self.variables.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2684)

**Comment by jaredlockhart** [comment]
We should probably validate the schema of features as part of desktop's tests, but we should also modify the loader to expect that field may not be present.

Filed for desktop: https://bugzilla.mozilla.org/show_bug.cgi?id=1784923

**Comment by jaredlockhart** [comment]
This patch will temporarily fix it for the new feature:

https://phabricator.services.mozilla.com/D154672

**Comment by jaredlockhart** [comment]
Oh nevermind it's blocking deploys

https://sentry.io/organizations/mozilla/issues/3504166313/?query=is%3Aunresolved

**Comment by jaredlockhart** [comment]
Fixed in https://github.com/mozilla/experimenter/pull/7600
