### ISSUE TITLE
Intermittent test failure:   PageHome › displays five Directory Tables (one for each status type)

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8120]
Seen here:

https://app.circleci.com/pipelines/github/mozilla/experimenter/19055/workflows/f7da2554-6e33-426c-8d17-9da662d6d1b7/jobs/56653

```
PageHome › displays five Directory Tables (one for each status type)

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      62 |     ] as const;
      63 |
    > 64 |   it("displays five Directory Tables (one for each status type)", async () => {
         |   ^
      65 |     await renderAndWaitForLoaded();
      66 |     // renders all experiments
      67 |     expect(screen.queryAllByTestId("DirectoryTable")).toHaveLength(6);

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/components/PageHome/index.test.tsx:64:3)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:26:1)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  ● PageHome › supports updating search params when tabs are clicked

    TestingLibraryElementError: Unable to find an element with the text: Review (1). This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div
          style="outline: none;"
          tabindex="-1"
        >
          <div
            props="[object Object]"
          >
            <p
              class="p-3"
            >
              Location:
               
              <code
                data-testid="location"
              >
                /demo-slug/edit
                
              </code>
            </p>
            <main
              class="h-100 pt-3 container-fluid"
              data-testid="PageHome"
              id="PageHome-page"
            >
              <div
                class="h-100 container-fluid mx-auto"
              >
                <svg
                  aria-label="nimbus logo"
                  class="float-left pb-1"
                  dominant-baseline="start"
                  fill="white"
                  height="85"
                  role="img"
                  width="100"
                >
                  logo.svg
                </svg>
                <h2
                  class="mb-3 text-left pt-4"
                >
                  Nimbus Experiments 
                </h2>
                <div
                  class="fade mb-4 mt-4 alert alert-primary show"
                  role="alert"
                >
                  <div>
                    <span
                      aria-label="book emoji"
                      role="img"
                    >
                      📖
                    </span>
                     
                    Not sure where to start? Check out the
                     
                    <a
                      data-testid="link-external"
                      href="https://experimenter.info"
                      rel="noopener noreferrer"
                      target="_blank"
                    >
                      Experimenter documentation hub.
                      <span
                        class="sr-only"
                      >
                        Opens in new window
                      </span>
                    </a>
                  </div>
                  <div>
                    <span
                      aria-label="magnifying emoji"
                      role="img"
                    >
                      🔍
                    </span>
                     
                    Looking for the old Experimenter?
                     
                    <a
                      data-testid="link-external"
                      href="/legacy"
                      id="legacy_page_link"
                      rel="noopener noreferrer"
                      target="_blank"
                    >
                      It‘s still here!
                      <span
                        class="sr-only"
                      >
                        Opens in new window
                      </span>
                    </a>
                    <span
                      aria-label="magnifying emoji"
                      role="img"
                    >
                      💡
                    </span>
                     
                    Have feedback?
                     
                    <a
                      data-testid="link-external"
                      href="https://mozilla-hub.atlassian.net/secure/CreateIssueDetails!init.jspa?pid=10203&issuetype=10097"
                      rel="noopener noreferrer"
                      target="_blank"
                    >
                      Please file it here!
                      <span
                        class="sr-only"
                      >
                        Opens in new window
                      </span>
                    </a>
                  </div>
                </div>
                <div
                  class="h-100vh container-fluid"
                >
                  <div
                    class="h-md-100 row"
                  >
                    <div
                      class="bg-light pt-2 border-right shadow-sm col-xl-2 col-lg-3 col-md-3"
                    >
                      <div
                        class="row"
                      >
                        <div
                          class="col"
                        >
                          <a
                            class="btn btn-primary btn-small mt-2 w-100"
                            data-sb-kind="pages/New"
                            href="/demo-slug/edit/new"
                            id="create-new-button"
                          >
                            <svg
                              aria-label="download icon"
                              dominant-baseline="start"
                              fill="white"
                              height="20"
                              role="img"
                              width="20"
                            >
                              pencil.svg
                            </svg>
                            <span
                              class="ml-1 pl-1"
                            >
                              Create New 
                            </span>
                          </a>
                        </div>
                      </div>
                      <div
                        class="row"
                      >
                        <div
                          class="col"
                        >
                          <a
                            class="btn btn-secondary btn-small mt-3 w-100"
                            data-testid="reports-anchor"
                            href="/api/v5/csv"
                          >
                            <svg
                              aria-label="download icon"
                              dominant-baseline="start"
                              fill="white"
                              height="20"
                              role="img"
                              width="20"
                            >
                              download.svg
                            </svg>
                            <span>
                               Reports
                            </span>
                          </a>
                        </div>
                      </div>
                      <div
                        class="row"
                      >
                        <div
                          class="col"
                        >
                          <h5
                            class="mt-3"
                          >
                            Filters
                          </h5>
                          <div
                            class="mb-2 input-group"
                          >
                            <div
                              class="input-group-prepend"
                            >
                              <span
                                class="input-group-text"
                              >
                                <svg
                                  aria-label="search icon"
                                  height="15"
                                  role="img"
                                  width="15"
                                >
                                  search.svg
                                </svg>
                              </span>
                            </div>
                            <input
                              aria-describedby="inputGroup-sizing-default"
                              aria-label="Default"
                              class="form-control"
                              data-testid="SearchExperiments"
                              placeholder="Search"
                              style="border-top-right-radius: 4px; border-bottom-right-radius: 4px;"
                              type="text"
                              value=""
                            />
                          </div>
                          <nav
                            class="nav-fill mb-4 navbar navbar-expand navbar-light bg-light"
                            style="padding: 0px;"
                          >
                            <div
                              class="w-100 flex-column navbar-nav"
                            >
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Features
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-allFeatureConfigs"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-allFeatureConfigs"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Applications
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-applications"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-applications"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Owners
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-owners"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-owners"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Versions
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-firefoxVersions"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-firefoxVersions"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Channels
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-channels"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-channels"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Types
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-types"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-types"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Team Projects
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-projects"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-projects"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                              <div
                                class="mb-2 text-left flex-basis-0 flex-grow-1 flex-shrink-1 w-100 nav-item"
                              >
                                <div
                                  class=" css-2b097c-container"
                                >
                                  <span
                                    aria-atomic="false"
                                    aria-live="polite"
                                    aria-relevant="additions text"
                                    class="css-1f43avz-a11yText-A11yText"
                                  />
                                  <div
                                    class=" css-yk16xz-control"
                                  >
                                    <div
                                      class=" css-g1d714-ValueContainer"
                                    >
                                      <div
                                        class=" css-1wa3eu0-placeholder"
                                      >
                                        All Audiences
                                      </div>
                                      <div
                                        class="css-b8ldur-Input"
                                      >
                                        <div
                                          class=""
                                          style="display: inline-block;"
                                        >
                                          <input
                                            aria-autocomplete="list"
                                            autocapitalize="none"
                                            autocomplete="off"
                                            autocorrect="off"
                                            id="filter-targetingConfigs"
                                            spellcheck="false"
                                            style="box-sizing: content-box; width: 2px; border: 0px; font-size: inherit; opacity: 1; outline: 0; padding: 0px;"
                                            tabindex="0"
                                            type="text"
                                            value=""
                                          />
                                          <div
                                            style="position: absolute; top: 0px; left: 0px; visibility: hidden; height: 0px; overflow: scroll; white-space: pre; font-size: inherit; font-family: -webkit-small-control; letter-spacing: normal; text-transform: none;"
                                          />
                                        </div>
                                      </div>
                                    </div>
                                    <div
                                      class=" css-1hb7zxy-IndicatorsContainer"
                                    >
                                      <span
                                        class=" css-1okebmr-indicatorSeparator"
                                      />
                                      <div
                                        aria-hidden="true"
                                        class=" css-tlfecz-indicatorContainer"
                                      >
                                        <svg
                                          aria-hidden="true"
                                          class="css-tj5bde-Svg"
                                          focusable="false"
                                          height="20"
                                          viewBox="0 0 20 20"
                                          width="20"
                                        >
                                          <path
                                            d="M4.516 7.548c0.436-0.446 1.043-0.481 1.576 0l3.908 3.747 3.908-3.747c0.533-0.481 1.141-0.446 1.574 0 0.436 0.445 0.408 1.197 0 1.615-0.406 0.418-4.695 4.502-4.695 4.502-0.217 0.223-0.502 0.335-0.787 0.335s-0.57-0.112-0.789-0.335c0 0-4.287-4.084-4.695-4.502s-0.436-1.17 0-1.615z"
                                          />
                                        </svg>
                                      </div>
                                    </div>
                                  </div>
                                  <div>
                                    <input
                                      name="filter-targetingConfigs"
                                      type="hidden"
                                    />
                                  </div>
                                </div>
                              </div>
                            </div>
                          </nav>
                        </div>
                      </div>
                    </div>
                    <div
                      class="col-xl-10 col-lg-9 col-md-9"
                    >
                      <main
                        class="h-100 pt-3 container-fluid"
                        data-testid="page-loading"
                        id="page-loading-page"
                      >
                        <div
                          class="h-100 container-fluid mx-auto"
                        >
                          <div
                            class="text-center"
                          >
                            <div
                              class="spinner-border text-primary"
                              data-testid="spinner"
                              role="status"
                            >
                              <span
                                class="sr-only"
                              >
                                Loading...
                              </span>
                            </div>
                          </div>
                        </div>
                      </main>
                    </div>
                  </div>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>
    </body>

      44 |   const findTabs = () =>
      45 |     [
    > 46 |       ["review", screen.getByText("Review (1)")],
         |                         ^
      47 |       ["preview", screen.getByText("Preview (1)")],
      48 |       ["completed", screen.getByText("Completed (4)")],
      49 |       ["drafts", screen.getByText("Draft (3)")],

      at Object.getElementError (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/config.js:37:19)
      at ../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:90:38
      at ../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:62:17
      at getByText (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:111:19)
      at findTabs (src/components/PageHome/index.test.tsx:46:25)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:91:33)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3044)

**Comment by eliserichards** [comment]
[another example](https://app.circleci.com/pipelines/github/mozilla/experimenter/19059/workflows/a545ecb3-389c-4cfa-b0b4-4691fa756ede/jobs/56679)

**Comment by yashikakhurana** [comment]
already done!
