### ISSUE TITLE
Failure while loading configs

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8247]
Looks like after we merged https://github.com/mozilla/experimenter/commit/69db23b4336d1e48dc4c46d0dfe5f5cf94c90796 the migration is crashing on startup.  It didn't get reported to sentry unfortunately, but we have the traceback from gcp:

```
"Traceback (most recent call last):
  File "/app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)"
 File "/app/experimenter/features/management/commands/load_feature_configs.py", line 52, in handle
    experimenter.experiments.models.NimbusFeatureConfig.MultipleObjectsReturned: get() returned more than one NimbusFeatureConfig -- it returned 2!
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3129)

**Comment by jaredlockhart** [comment]
Features are unique on (application, slug)

https://github.com/mozilla/experimenter/blob/main/app/experimenter/experiments/models.py#L1016

so we have to include application when querying them 👍
