### ISSUE TITLE
Remote kinto_mailer from kinto.ini

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#8275]
Looks like the remote-settings docker image is having trouble starting:

```
experimenter-kinto-1  | The account plugin works really poorly with the memory backend because accounts are flushed at each startup.
experimenter-kinto-1  | This is why you can't use the kinto create-user command with it.
experimenter-kinto-1  | Traceback (most recent call last):
experimenter-kinto-1  |   File "app.wsgi", line 30, in <module>
experimenter-kinto-1  |     application = main(config.items('DEFAULT'), **dict(config.items('app:main')))
experimenter-kinto-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/kinto/__init__.py", line 51, in main
experimenter-kinto-1  |     kinto.core.initialize(config, version=__version__, default_settings=DEFAULT_SETTINGS)
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/kinto/core/initialization.py", line 618, in initialize
experimenter-kinto-1  |     config.include("kinto.core", route_prefix=api_version)
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/pyramid/config/__init__.py", line 666, in include
experimenter-kinto-1  |     c(configurator)
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/kinto/core/__init__.py", line 218, in includeme
experimenter-kinto-1  |     config.include(app)
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/pyramid/config/__init__.py", line 666, in include
experimenter-kinto-1  |     c(configurator)
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/kinto_emailer/__init__.py", line 192, in includeme
experimenter-kinto-1  |     config.include('pyramid_mailer' + ('.debug' if debug else ''))
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/pyramid/config/__init__.py", line 666, in include
experimenter-kinto-1  |     c(configurator)
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/pyramid_mailer/debug.py", line 8, in includeme
experimenter-kinto-1  |     mailer = DebugMailer(path)
experimenter-kinto-1  |              ^^^^^^^^^^^^^^^^^
experimenter-kinto-1  |   File "/opt/venv/lib/python3.11/site-packages/pyramid_mailer/mailer.py", line 40, in __init__
experimenter-kinto-1  |     makedirs(top_level_directory)
experimenter-kinto-1  |   File "<frozen os>", line 225, in makedirs
experimenter-kinto-1  | PermissionError: [Errno 13] Permission denied: '/app/mail'
experimenter-kinto-1  | unable to load app 0 (mountpoint='') (callable not found or import error)
```

We don't need this mailer component for local dev or ci, so let's just remove it from kinto.ini

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3142)

**Comment by jaredlockhart** [comment]
This does not seem to fix it, closing this.
