### ISSUE TITLE
Something is lingering inside the Celery worker

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#947]
When I SIGTERM the celery worker I get this output:

<details>
<summary>When SIGTERM'ing the Celery worker</summary>
^CSIGINT received
sending SIGTERM to web.1 (pid 44921)
sending SIGTERM to celery.1 (pid 44922)

worker: Warm shutdown (MainProcess)
[2019-02-19 18:24:39,461: DEBUG/MainProcess] Canceling task consumer...
web.1 stopped (rc=-15)
[2019-02-19 18:24:40,471: DEBUG/MainProcess] Canceling broadcast consumer...
[2019-02-19 18:24:40,473: WARNING/MainProcess] Traceback (most recent call last):
[2019-02-19 18:24:40,474: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
[2019-02-19 18:24:40,481: WARNING/MainProcess] self.blueprint.start(self)
[2019-02-19 18:24:40,481: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
[2019-02-19 18:24:40,482: WARNING/MainProcess] step.start(parent)
[2019-02-19 18:24:40,482: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
[2019-02-19 18:24:40,482: WARNING/MainProcess] return self.obj.start()
[2019-02-19 18:24:40,483: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 317, in start
[2019-02-19 18:24:40,483: WARNING/MainProcess] blueprint.start(self)
[2019-02-19 18:24:40,484: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
[2019-02-19 18:24:40,484: WARNING/MainProcess] step.start(parent)
[2019-02-19 18:24:40,484: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 593, in start
[2019-02-19 18:24:40,484: WARNING/MainProcess] c.loop(*c.loop_args())
[2019-02-19 18:24:40,485: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/loops.py", line 91, in asynloop
[2019-02-19 18:24:40,485: WARNING/MainProcess] next(loop)
[2019-02-19 18:24:40,485: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 306, in create_loop
[2019-02-19 18:24:40,486: WARNING/MainProcess] events = poll(poll_timeout)
[2019-02-19 18:24:40,487: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/utils/eventio.py", line 217, in poll
[2019-02-19 18:24:40,487: WARNING/MainProcess] event_list = self._quick_poll(timeout)
[2019-02-19 18:24:40,488: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/apps/worker.py", line 284, in _handle_request
[2019-02-19 18:24:40,489: WARNING/MainProcess] raise exc(exitcode)
[2019-02-19 18:24:40,489: WARNING/MainProcess] celery.exceptions
[2019-02-19 18:24:40,489: WARNING/MainProcess] .
[2019-02-19 18:24:40,489: WARNING/MainProcess] WorkerShutdown
[2019-02-19 18:24:40,489: WARNING/MainProcess] :
[2019-02-19 18:24:40,489: WARNING/MainProcess] 0
[2019-02-19 18:24:40,489: WARNING/MainProcess] During handling of the above exception, another exception occurred:
[2019-02-19 18:24:40,489: WARNING/MainProcess] Traceback (most recent call last):
[2019-02-19 18:24:40,489: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/bin/celery", line 10, in <module>
[2019-02-19 18:24:40,490: WARNING/MainProcess] sys.exit(main())
[2019-02-19 18:24:40,490: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/__main__.py", line 16, in main
[2019-02-19 18:24:40,490: WARNING/MainProcess] _main()
[2019-02-19 18:24:40,490: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/celery.py", line 322, in main
[2019-02-19 18:24:40,491: WARNING/MainProcess] cmd.execute_from_commandline(argv)
[2019-02-19 18:24:40,492: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
[2019-02-19 18:24:40,492: WARNING/MainProcess] super(CeleryCommand, self).execute_from_commandline(argv)))
[2019-02-19 18:24:40,492: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/base.py", line 275, in execute_from_commandline
[2019-02-19 18:24:40,493: WARNING/MainProcess] return self.handle_argv(self.prog_name, argv[1:])
[2019-02-19 18:24:40,493: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/celery.py", line 488, in handle_argv
[2019-02-19 18:24:40,494: WARNING/MainProcess] return self.execute(command, argv)
[2019-02-19 18:24:40,494: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/celery.py", line 420, in execute
[2019-02-19 18:24:40,495: WARNING/MainProcess] ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2019-02-19 18:24:40,495: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv
[2019-02-19 18:24:40,495: WARNING/MainProcess] return self(*args, **options)
[2019-02-19 18:24:40,496: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/base.py", line 238, in __call__
[2019-02-19 18:24:40,496: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2019-02-19 18:24:40,496: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bin/worker.py", line 258, in run
[2019-02-19 18:24:40,496: WARNING/MainProcess] worker.start()
[2019-02-19 18:24:40,496: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/worker.py", line 212, in start
[2019-02-19 18:24:40,496: WARNING/MainProcess] self.stop(exitcode=exc.code)
[2019-02-19 18:24:40,496: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/worker.py", line 253, in stop
[2019-02-19 18:24:40,497: WARNING/MainProcess] self._shutdown(warm=True)
[2019-02-19 18:24:40,497: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/worker.py", line 268, in _shutdown
[2019-02-19 18:24:40,497: WARNING/MainProcess] self.blueprint.stop(self, terminate=not warm)
[2019-02-19 18:24:40,497: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bootsteps.py", line 177, in stop
[2019-02-19 18:24:40,497: WARNING/MainProcess] self.on_stopped()
[2019-02-19 18:24:40,497: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/worker.py", line 164, in on_stopped
[2019-02-19 18:24:40,497: WARNING/MainProcess] self.consumer.shutdown()
[2019-02-19 18:24:40,497: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 352, in shutdown
[2019-02-19 18:24:40,498: WARNING/MainProcess] self.blueprint.shutdown(self)
[2019-02-19 18:24:40,498: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 159, in shutdown
[2019-02-19 18:24:40,498: WARNING/MainProcess] self.send_all(parent, 'shutdown')
[2019-02-19 18:24:40,498: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/bootsteps.py", line 151, in send_all
[2019-02-19 18:24:40,498: WARNING/MainProcess] fun(parent, *args)
[2019-02-19 18:24:40,498: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/pidbox.py", line 78, in shutdown
[2019-02-19 18:24:40,499: WARNING/MainProcess] self.stop(self.c)
[2019-02-19 18:24:40,499: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/pidbox.py", line 63, in stop
[2019-02-19 18:24:40,499: WARNING/MainProcess] self.consumer = self._close_channel(c)
[2019-02-19 18:24:40,499: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/celery/worker/pidbox.py", line 71, in _close_channel
[2019-02-19 18:24:40,499: WARNING/MainProcess] ignore_errors(c, self.node.channel.close)
[2019-02-19 18:24:40,499: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/common.py", line 295, in ignore_errors
[2019-02-19 18:24:40,500: WARNING/MainProcess] return fun(*args, **kwargs)
[2019-02-19 18:24:40,500: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/transport/redis.py", line 853, in close
[2019-02-19 18:24:40,501: WARNING/MainProcess] self._close_clients()
[2019-02-19 18:24:40,501: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/transport/redis.py", line 862, in _close_clients
[2019-02-19 18:24:40,501: WARNING/MainProcess] connection.disconnect()
[2019-02-19 18:24:40,501: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/transport/redis.py", line 941, in disconnect
[2019-02-19 18:24:40,502: WARNING/MainProcess] channel._on_connection_disconnect(self)
[2019-02-19 18:24:40,502: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/transport/redis.py", line 546, in _on_connection_disconnect
[2019-02-19 18:24:40,502: WARNING/MainProcess] self.connection.cycle._on_connection_disconnect(connection)
[2019-02-19 18:24:40,502: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/transport/redis.py", line 1054, in _on_disconnect
[2019-02-19 18:24:40,503: WARNING/MainProcess] loop.remove(connection._sock)
[2019-02-19 18:24:40,503: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 181, in remove
[2019-02-19 18:24:40,503: WARNING/MainProcess] self._remove_from_loop(fd)
[2019-02-19 18:24:40,503: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 160, in _remove_from_loop
[2019-02-19 18:24:40,503: WARNING/MainProcess] self._unregister(fd)
[2019-02-19 18:24:40,503: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 243, in _unregister
[2019-02-19 18:24:40,503: WARNING/MainProcess] self.poller.unregister(fd)
[2019-02-19 18:24:40,503: WARNING/MainProcess] File "/Users/peterbe/virtualenvs/experimenter/lib/python3.7/site-packages/kombu/utils/eventio.py", line 209, in unregister
[2019-02-19 18:24:40,503: WARNING/MainProcess] self._quick_unregister(fd)
[2019-02-19 18:24:40,503: WARNING/MainProcess] ValueError
[2019-02-19 18:24:40,503: WARNING/MainProcess] :
[2019-02-19 18:24:40,504: WARNING/MainProcess] file descriptor cannot be a negative integer (-1)
[2019-02-19 18:24:40,504: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
</details>

No idea what it means but it smells like an unclosed file descriptor or something.

**Comment by peterbe** [comment]
According to this: https://github.com/celery/celery/issues/5248#issuecomment-449963440 it got resolved by upgrading billiard. 

We currently have 3.5.0.5 and the latest version is 3.6.0.0.

**Comment by peterbe** [comment]
See https://github.com/mozilla/experimenter/pull/988

**Comment by peterbe** [comment]
I don't think that PR should automatically close this. We'll just see if the problem goes away once we upgrade stuff.

**Comment by jaredkerim** [comment]
I'm closing this, if it surfaces as an issue we can file a new bug.
