### ISSUE TITLE
Cirrus does not start locally with sample configuration

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9625]
Using the [sample configuration](https://github.com/mozilla/experimenter/blob/main/.env.sample#L53-L66) I am getting the following output from Cirrus:

```py
experimenter-cirrus-1  | INFO:     Started server process [7]
experimenter-cirrus-1  | INFO:     Waiting for application startup.
experimenter-cirrus-1  | ERROR:    Traceback (most recent call last):
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/_uniffi.py", line 424, in check
experimenter-cirrus-1  |     value = value.__index__()
experimenter-cirrus-1  |             ^^^^^^^^^^^^^^^
experimenter-cirrus-1  | AttributeError: 'str' object has no attribute '__index__'
experimenter-cirrus-1  | 
experimenter-cirrus-1  | During handling of the above exception, another exception occurred:
experimenter-cirrus-1  | 
experimenter-cirrus-1  | Traceback (most recent call last):
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
experimenter-cirrus-1  |     async with self.lifespan_context(app) as maybe_state:
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
experimenter-cirrus-1  |     return await anext(self.gen)
experimenter-cirrus-1  |            ^^^^^^^^^^^^^^^^^^^^^
experimenter-cirrus-1  |   File "/app/cirrus/main.py", line 46, in lifespan
experimenter-cirrus-1  |     app.state.pings, app.state.metrics = initialize_glean()
experimenter-cirrus-1  |                                          ^^^^^^^^^^^^^^^^^^
experimenter-cirrus-1  |   File "/app/cirrus/main.py", line 117, in initialize_glean
experimenter-cirrus-1  |     Glean.initialize(
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/glean.py", line 237, in initialize
experimenter-cirrus-1  |     _uniffi.glean_initialize(cfg, client_info, callbacks)
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/_uniffi.py", line 5716, in glean_initialize
experimenter-cirrus-1  |     FfiConverterTypeInternalConfiguration.lower(cfg),
experimenter-cirrus-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/_uniffi.py", line 455, in lower
experimenter-cirrus-1  |     cls.write(value, builder)
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/_uniffi.py", line 4163, in write
experimenter-cirrus-1  |     FfiConverterOptionalUInt32.write(value.max_events, buf)
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/_uniffi.py", line 5186, in write
experimenter-cirrus-1  |     FfiConverterUInt32.write(value, buf)
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/_uniffi.py", line 418, in write
experimenter-cirrus-1  |     cls.writeUnchecked(cls.check(value), buf)
experimenter-cirrus-1  |                        ^^^^^^^^^^^^^^^^
experimenter-cirrus-1  |   File "/usr/local/lib/python3.11/site-packages/glean/_uniffi.py", line 426, in check
experimenter-cirrus-1  |     raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
experimenter-cirrus-1  | TypeError: 'str' object cannot be interpreted as an integer
experimenter-cirrus-1  | 
experimenter-cirrus-1  | ERROR:    Application startup failed. Exiting.
experimenter-cirrus-1 exited with code 3
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3960)

**Comment by jaredlockhart** [comment]
This seems to be a regression introduced in https://github.com/mozilla/experimenter/pull/9622 and isn't in main, closing.
