### ISSUE TITLE
Intermittent test failure: PageHome › supports filtering by feature

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#9673]
Seen locally

```js
FAIL src/components/PageHome/index.test.tsx (16.798s)
  ● PageHome › supports filtering by feature

    Timed out in waitForElementToBeRemoved.


      190 | ) => {
      191 |   render(<Subject {...{ experiments }} />);
    > 192 |   await waitForElementToBeRemoved(() => screen.getByTestId("page-loading"));
          |                                  ^
      193 | };
      194 |

      at waitForElementToBeRemoved (../../node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for-element-to-be-removed.js:22:24)
      at renderAndWaitForLoaded (src/components/PageHome/index.test.tsx:192:34)
      at Object.<anonymous> (src/components/PageHome/index.test.tsx:145:11)
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3992)

**Comment by jaredlockhart** [comment]
We haven't seen this in a while.  Closing for now and we can refile if we see it again.
